services:
  - type: web
    name: live-score-api
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_TZ
        value: Asia/Kolkata
      - key: APP_LIST_CACHE_TTL_SECONDS
        value: "20"
      - key: APP_DETAIL_CACHE_TTL_SECONDS
        value: "20"
      - key: APP_FETCH_TIMEOUT_SECONDS
        value: "12"
